[package]
name = "cryptid"
version = "0.9.0"
authors = ["Eleanor McMurtry <elmcmurtry1@gmail.com>"]
edition = "2018"
description = "An implementation of the threshold ElGamal cryptosystem with zero-knowledge proofs, using Ristretto255 as the group."
license = "Apache-2.0"
repository = "https://github.com/noneuclideangirl/cryptid"

[dependencies]
rand_core = { version = "0.6", default_features = false }
rust-elgamal = { version = "0.3", features = ["enable-serde"] }
serde = { version = "1", default_features = false, features = ["derive"] }
sha2 = "0.9"
zkp = "0.8"
# Temporary until I figure out what's going on with hdevalence and *-ng
curve25519-dalek = { package = "curve25519-dalek-ng", version = "3", default-features = false, features = ["serde", "std"] }

[dev-dependencies]
bincode = "1"
rand = { version = "0.8" }
