[package]
name = "cryptid"
version = "0.5.0"
authors = ["Eleanor McMurtry <elmcmurtry1@gmail.com>"]
edition = "2018"
description = "An implementation of the threshold ElGamal cryptosystem with zero-knowledge proofs, using Curve25519 as the group."
license = "MIT"
repository = "https://github.com/noneuclideangirl/cryptid"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
num-bigint = { version = "0", features = ["rand", "serde"] }
ring = "0"
curve25519-dalek = { version = "2", features = ["serde", "simd_backend"] }
num-traits = "0"
base64 = "0"
rand_chacha = "0"
rand = "0"