[package]
name = "cryptid"
version = "0.2.3"
authors = ["Eleanor McMurtry <elmcmurtry1@gmail.com>"]
edition = "2018"
description = "An implementation of the threshold ElGamal cryptosystem with zero-knowledge proofs, using Curve25519 as the group."
license = "MIT"
repository = "https://github.com/noneuclideangirl/cryptid"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
num-bigint = { version = "0.2.6", features = ["rand", "serde"] }
ring = "0.16.13"
curve25519-dalek = { version = "2.0.0", features = ["serde"] }
num-traits = "0.2.11"
base64 = "0.12.1"
